# Generated by Django 5.2.8 on 2025-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('questionId', models.UUIDField()),
                ('text', models.TextField()),
                ('isCorrect', models.BooleanField()),
            ],
            options={
                'db_table': 'Answer',
                'managed': True,
            },
        ),
    ]
