# Generated by Django 5.2.8 on 2025-12-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': False},
        ),
    ]
